### ISSUE TITLE
Support for gatsby v2

### ISSUE THREAD

**Issue by awidjaja** [kevzettler/gatsby-source-airtable#11]
Almost all plugins were updated with @next tag to support gatsby v2, except this plugin. 
Is there a timeline?

**Comment by kishanio** [comment]
@awidjaja Is this plugin supported with Gatsby v2? I tried integrating it and couldn't get it working.

**Comment by awidjaja** [comment]
@kishanio, no it won't work with gatsby v2. You will need to install it as local plugin and migrate all the dependencies to v2.

**Comment by jbolda** [comment]
FYI, I just pushed a beta version for v2 on [gatsby-source-airtable-linked](https://github.com/jbolda/gatsby-source-airtable-linked) on the `next` tag. It may be of interest rather than maintaining your own.

**Comment by kevzettler** [comment]
@jbolda thanks for the heads up I need to confirm if I'm using this in any production applications and I can give you the `gatsby-source-airtable` namespace. 

And honestly, I would have been cool adding you as a maintainer here if you opened up a PR that was a complete rewrite to this repo instead of creating a new name.

**Comment by jbolda** [comment]
@kevzettler sounds good, we can talk (here or whatever medium you prefer, website has all contact info).

I needed a handful of new features which were best as breaking changes and effectively changed your assumptions. I was just getting things done at the time, and that was the fastest path forward. It would have been awkward breaking everything on a minor version, and it is handy keeping the major version pegged to gatsby. Plus it was worth proving there was value to even doing this in the first place (if not just to myself). Now that it has been a handful of months, and gatsby@v2 is nearing release, perhaps it makes sense now. Apologies if I misread the situation and/or offended you in any way.
