### ISSUE TITLE
Support for Gatsby 2 

### ISSUE THREAD

**Issue by kishanio** [kevzettler/gatsby-source-airtable#13]
Right now after integrating plugin with Gatsby 2 following error is encountered. `ReferenceError: regeneratorRuntime is not defined`

**Comment by jbolda** [comment]
@kishanio I just published a new version on the `next` tag. Please give it a whirl. We are combining namespaces and there are breaking changes for v2. The docs are currently most accessible at [jbolda/gatsby-source-airtable](https://github.com/jbolda/gatsby-source-airtable) as npm doesn't show the `next` tag by default.

**Comment by jbolda** [comment]
v2 has been published. Feel free to open a new issue if you have questions.
