### ISSUE TITLE
Different tables, same field name, but different types

### ISSUE THREAD

**Issue by chrisblow** [kevzettler/gatsby-source-airtable#14]
It's possible this is expected behavior somehow, or I'm configuring it wrong. Feedback welcome.

### Problem

I have a base where different tables have the same field name, but different types. Sometimes (one field is array-type/multiple choice and the other field is string-type/single choice) this is handled gracefully with a warning. But other times (one is a number and one is a string) the error was an `unhandled rejection` that was difficult to track down. 

### Temporary solution

I had to change the field types to match, and in the future I'll have to manually check to make sure that new field types don't conflict with any of the existing fields.

### Better solutions

• I was surprised that the field names conflict at all. Perhaps this could be avoided somehow. 
• Alternatively, I would expect there to always be a friendly warning about conflicting types, not an unhandled rejection.

### Extra details:

**The friendly warning was like this**

This is what happens with `Array[string]` type (multiple choice) vs. `String` (single choice) type conflicts.

(Ideally this warning would include the name of both tables involved — currently it only shows one of the table names.)

```
warning There are conflicting field types in your data. GraphQL schema will omit those fields.
Airtable.data.Sector:
 - type: array<string>
   value: [ 'Life Sciences' ]
 - type: string
   value: 'Materials'
```

**The unhandled rejection:**

This is what happens with a `Number` type vs. `String` type conflict.
```
error gatsby-node.js returned an error


  TypeError: Cannot read property 'publicProjectsAndOrganizations' of undefined

  - gatsby-node.js:306 graphql.then.result
    /Users/chrisblow/git/thedataguild.com/gatsby-node.js:306:21

  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:606 Promise._settlePromiseCtx
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:606:10

  - async.js:138 Async._drainQueue
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:138:12

  - async.js:143 Async._drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:143:10

  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14


error UNHANDLED REJECTION


  TypeError: Cannot read property 'filter' of undefined

  - api-runner-node.js:274 Promise.mapSeries.catch.then.results
    [thedataguild.com]/[gatsby]/dist/utils/api-runner-node.js:274:42

  - util.js:16 tryCatcher
    [thedataguild.com]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [thedataguild.com]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [thedataguild.com]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [thedataguild.com]/[bluebird]/js/release/promise.js:614:10

  - promise.js:693 Promise._settlePromises
    [thedataguild.com]/[bluebird]/js/release/promise.js:693:18

  - async.js:133 Async._drainQueue
    [thedataguild.com]/[bluebird]/js/release/async.js:133:16

  - async.js:143 Async._drainQueues
    [thedataguild.com]/[bluebird]/js/release/async.js:143:10

  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [thedataguild.com]/[bluebird]/js/release/async.js:17:14
```

**Comment by kevzettler** [comment]
cc @jbolda

**Comment by kevzettler** [comment]
@chrisblow please see readme

https://github.com/kevzettler/gatsby-source-airtable#we-are-combining-namespaces-this-repo-is-deprecated-in-favor-of-jboldagatsby-source-airtable-for-gatsby-v2-the-change-will-be-transparent-to-npm-but-all-documentation-and-any-new-issues-should-be-created-at-the-new-github-repo

**Comment by chrisblow** [comment]
Oops thanks, moving it.
