### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by kosirm** [kevzettler/gatsby-source-airtable#4]
Hi, thanks for sharing this gatsby plugin! It would be great if there would be simple example/starter for beginners, like me 😄 

I would like to create a multilingual site and put site text into Airtable, so it would be simple to translate all site text in one place.

Do you think this is possible with your plugin?

**Comment by kevzettler** [comment]
Hi Kosirm,

> Do you think this is possible with your plugin? 
Probably, you will need to implement a translation layer on top of the Airtable content.

> It would be great if there would be simple example/starter for beginners, like me 😄
The excellent Gatsby documentation at https://www.gatsbyjs.org/docs/  will get you up and running and walk you through installing plugins. You can then install this Airtable plugin.

**Comment by kosirm** [comment]
Thanks, sorry for using issues as help system 😄 
Still, it would be great if you could create a simple starter for us beginners...
All the best!
