### ISSUE TITLE
Example of using multiple bases/tables?

### ISSUE THREAD

**Issue by mikecrittenden** [kevzettler/gatsby-source-airtable#8]
Looking at the code, it seems like it's possible to expose multiple Airtable bases or tables, but I can't seem to find the right combination of config in `gatsby-config.js` to enable that.

Note that I don't mean using multiple bases/tables in the same query, I just mean exposing multiple tables/bases in general, so that you're not limited to only a single table.

**Comment by mikecrittenden** [comment]
Never mind, just figured out that you just create another plugin object in `gatsby-config.js` like so:

```
    {   
      resolve: `gatsby-source-airtable`,
      options: {
        apiKey: `APIKEY`,
        baseId: `Base ID 1`,
        tableName: `Table 1`,
        tableView: `View 1`,
        queryName: `Query 1`
      }   
    },  
    {   
      resolve: `gatsby-source-airtable`,
      options: {
        apiKey: `APIKEY`,
        baseId: `Base ID 2`,
        tableName: `Table 2`,
        tableView: `View 2`,
        queryName: `Query 2`
      }   
    },  
```

**Comment by kevzettler** [comment]
@mikecrittenden wow, I wasn't aware that would work! I've just assumed it was one table only. going to add that to the README thanks!

**Comment by mikecrittenden** [comment]
Yep, works perfectly!
